# Development values for marcstreeterdev-backend

# Development mode enabled (for probes)
dev:
  enabled: true

# Replica count for development
replicaCount: 1

# Service configuration
service:
  targetPort: 8000

# Resource limits
resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 128Mi
    cpu: 100m 