name: CI

on:
  push:
    branches: [main, "feature/**"]
  pull_request:
    branches: [main, "feature/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv pip install -r requirements.lock.txt

      - name: Build Docker image
        run: docker build -t fastapi-app .

      - name: Set up pre-commit
        run: |
          pip install pre-commit
          pre-commit install

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

      - name: Run tests
        run: uv pip run pytest 